### PR TITLE
Siguup startup

### PR DESCRIPTION
**Pull request by JaofourthsOhappy**

### CODE REVIEW

**Comment by oaoak** [comment]
I'm not sure those cjs, umd, and some those directories should be structured like that. I think it would be better to recheck.

**Review by oaoak — CHANGES_REQUESTED** [review]
I'm not sure those cjs, umd, and some those directories should be structured like that. I think it would be better to recheck.

**Review by zevenfox — COMMENTED** [review]
no push node module

**Comment by zevenfox** [comment]
the module should not push to production

**Pull request closed without merging**
